template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: {{ .Values.primaryResource }}
    type: GitRepo
    configuration:
      path: {{ .Values.repoPath }}
      gitProvider: {{ .Values.gitProvider }}
      branches:
        include: ^{{ .Values.mainBranch }}$
      cloneProtocol: {{ .Values.protocol }}
      buildOn:
        commit: {{ .Values.buildOnCommit }}

pipelines:
  - name: {{ .Values.pipelineName }}
    configuration:
      jfrogCliVersion: 2
      environmentVariables:
        readOnly:
          JFROG_TASK_DEBUG: "true"
          JFROG_CLI_LOG_LEVEL: debug
    steps:
      - name: test_{{.Values.taskName }}
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              auto:
                language: go
                version: 1.21
          inputResources:
            - name: {{ .Values.primaryResource }}
          integrations:
            - name: {{ .Values.artifactory }}
        execution:
          onStart:
            - echo "Starting execution on {{ .Values.taskName }}"
          onExecute:
            - echo "Starting onExecute"
            - pushd $res_{{ .Values.primaryResource }}_resourcePath
            - export GOPROXY="https://${int_{{ .Values.artifactory }}_user}:${int_{{ .Values.artifactory }}_apikey}@entplus.jfrog.io/artifactory/api/go/pipe-go-tasks-virtual"
            - echo $GOPROXY
            - export GONOSUMDB="github.com/jfrog/*"
            - go get .
            - make do-all
            - popd
            - task: $res_{{ .Values.primaryResource }}_resourcePath
              id: my-awesome-task
              input:
                step_names: 'step_1,step_2'
                environment_variables: "{\"key1\":\"value1\",\"key2\":\"value2\"}"
          onFailure:
            - echo "Task Test failed"
          onSuccess:
            - echo "Test Task execution is a success without any errors"
          onComplete:
            - echo "Test Task execution completed."